[2022-07-13 15:32:13,189] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: project_dag_v3.print_data manual__2022-07-13T15:30:07.645157+00:00 [queued]>
[2022-07-13 15:32:13,202] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: project_dag_v3.print_data manual__2022-07-13T15:30:07.645157+00:00 [queued]>
[2022-07-13 15:32:13,203] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-13 15:32:13,204] {taskinstance.py:1377} INFO - Starting attempt 2 of 6
[2022-07-13 15:32:13,205] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-13 15:32:13,219] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): print_data> on 2022-07-13 15:30:07.645157+00:00
[2022-07-13 15:32:13,225] {standard_task_runner.py:52} INFO - Started process 3525 to run task
[2022-07-13 15:32:13,229] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'project_dag_v3', 'print_data', 'manual__2022-07-13T15:30:07.645157+00:00', '--job-id', '82', '--raw', '--subdir', 'DAGS_FOLDER/project_dag.py', '--cfg-path', '/tmp/tmpo9713tae', '--error-file', '/tmp/tmpklq142sh']
[2022-07-13 15:32:13,231] {standard_task_runner.py:80} INFO - Job 82: Subtask print_data
[2022-07-13 15:32:13,302] {task_command.py:371} INFO - Running <TaskInstance: project_dag_v3.print_data manual__2022-07-13T15:30:07.645157+00:00 [running]> on host 3bcedaf5b66b
[2022-07-13 15:32:13,379] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=harshab
AIRFLOW_CTX_DAG_ID=project_dag_v3
AIRFLOW_CTX_TASK_ID=print_data
AIRFLOW_CTX_EXECUTION_DATE=2022-07-13T15:30:07.645157+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-13T15:30:07.645157+00:00
[2022-07-13 15:32:13,395] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/project_dag.py", line 30, in print_data
    df = pd.read_csv(data_csv_file)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 614, in get_handle
    storage_options=storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 396, in _get_filepath_or_buffer
    raise ValueError(msg)
ValueError: Invalid file path or buffer object type: <class 'NoneType'>
[2022-07-13 15:32:13,407] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=project_dag_v3, task_id=print_data, execution_date=20220713T153007, start_date=20220713T153213, end_date=20220713T153213
[2022-07-13 15:32:13,418] {standard_task_runner.py:97} ERROR - Failed to execute job 82 for task print_data (Invalid file path or buffer object type: <class 'NoneType'>; 3525)
[2022-07-13 15:32:13,442] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-13 15:32:13,479] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
